# Practical Exam: House sales

RealAgents is a real estate company that focuses on selling houses.

RealAgents sells a variety of types of house in one metropolitan area.

Some houses sell slowly and sometimes require lowering the price in order to find a buyer.

In order to stay competitive, RealAgents would like to optimize the listing prices of the houses it is trying to sell.

They want to do this by predicting the sale price of a house given its characteristics.

If they can predict the sale price in advance, they can decrease the time to sale.


## Data

The dataset contains records of previous houses sold in the area.

| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton'. </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced" (two shared walls), "Semi-detached" (one shared wall), or "Detached" (no shared walls). </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

# Task 1

The team at RealAgents knows that the city that a property is located in makes a difference to the sale price. 

Unfortuntately they believe that this isn't always recorded in the data. 

Calculate the number of missing values of the `city`. 

 - You should use the data in the file "house_sales.csv". 

 - Your output should be an object `missing_city`, that contains the number of missing values in this column.

In [36]:
"""
Project Name: House Sales Data Cleaning & Price Prediction
Description: 
    This script cleans house sales data, calculates price statistics by bedrooms, 
    and predicts house sale prices using linear regression and gradient boosting models. 
    It also preprocesses categorical and numerical features, handling missing data and 
    standardizing the dataset.

Author: Beulah Nwokotubo
Version: 1.0
Date Created: August 18, 2024

Steps:
    1. Data Cleaning: Replacing missing values, standardizing columns, and handling unconventional entries.
    2. Statistical Analysis: Calculating average sale price and variance by number of bedrooms.
    3. Model Training: Using Linear Regression and Gradient Boosting Regressor to predict house prices.
    4. Output: Comparing model predictions and generating a cleaned dataset for future use.

Dependencies:
    - pandas
    - scikit-learn
    - house_sales.csv, train.csv, validation.csv (data files)
"""

import pandas as pd

# Load the house_sales.csv file
house_sales = pd.read_csv('house_sales.csv')

# Calculate the number of missing values in the 'city' column
missing_city = (house_sales['city'] == '--').sum()

# Display the results
print(missing_city)

73

# Task 2 

Before you fit any models, you will need to make sure the data is clean. 

The table below shows what the data should look like. 

Create a cleaned version of the dataframe. 

 - You should start with the data in the file "house_sales.csv". 

 - Your output should be a dataframe named `clean_data`. 

 - All column names and values should match the table below.


| Column Name | Criteria                                                |
|-------------|---------------------------------------------------------|
| house_id    | Nominal. </br> Unique identifier for houses. </br>Missing values not possible. |
| city        | Nominal. </br>The city in which the house is located. One of 'Silvertown', 'Riverford', 'Teasdale' and 'Poppleton' </br>Replace missing values with "Unknown". |
| sale_price  | Discrete. </br>The sale price of the house in whole dollars. Values can be any positive number greater than or equal to zero.</br>Remove missing entries. |
| sale_date   | Discrete. </br>The date of the last sale of the house. </br>Replace missing values with 2023-01-01. |
| months_listed  | Continuous. </br>The number of months the house was listed on the market prior to its last sale, rounded to one decimal place. </br>Replace missing values with mean number of months listed, to one decimal place. |
| bedrooms    | Discrete. </br>The number of bedrooms in the house. Any positive values greater than or equal to zero. </br>Replace missing values with the mean number of bedrooms, rounded to the nearest integer. |
| house_type   | Ordinal. </br>One of "Terraced", "Semi-detached", or "Detached". </br>Replace missing values with the most common house type. |
| area      | Continuous. </br>The area of the house in square meters, rounded to one decimal place. </br>Replace missing values with the mean, to one decimal place. |

In [37]:

# Data Cleaning

# Check for missing values
house_sales['city'].isna().sum()
house_sales['sale_price'].isna().sum()
house_sales['sale_date'].isna().sum()
house_sales['months_listed'].isna().sum()
house_sales['bedrooms'].isna().sum()
house_sales['house_type'].isna().sum()
house_sales['area'].isna().sum()

# Replace missing 'city' with 'Unknown'
house_sales['city'].fillna('Unknown', inplace=True)
# Replace '--' in the 'city' column with 'Unknown'
house_sales['city'] = house_sales['city'].replace('--', 'Unknown')

# Remove rows with missing 'sale_price'
house_sales.dropna(subset=['sale_price'], inplace=True)

# Convert the sale_date column to datetime
house_sales['sale_date'] = pd.to_datetime(house_sales['sale_date'], errors='coerce')
# Limit 'sale_date' to only year, month, and day
house_sales['sale_date'] = house_sales['sale_date'].dt.strftime('%Y-%m-%d')
# To confirm the conversion
print(house_sales['sale_date'].dtype)  # Should output: datetime64[ns]
# Replace missing 'sale_date' with '2023-01-01'
house_sales['sale_date'].fillna('2023-01-01', inplace=True)

# Replace missing 'months_listed' with the mean (rounded to 1 decimal place)
# Convert 'months_listed' to numeric, ignoring 'NA'
house_sales['months_listed'] = pd.to_numeric(house_sales['months_listed'], errors='coerce')
# Calculate the mean of 'months_listed', excluding NaN values and round to 1 d.p.
mean_months_listed = house_sales['months_listed'].mean().round(1)
# Replace 'NA' with the mean value in 'months_listed'
house_sales['months_listed'].fillna(mean_months_listed, inplace=True)

# Replace missing 'bedrooms' with the mean (rounded to the nearest integer)
mean_bedrooms = house_sales['bedrooms'].astype(float).mean().round(0).astype(int)
house_sales['bedrooms'].fillna(mean_bedrooms, inplace=True)

# Clean and standardize the categorical/nominal columns
# Replace abbreviations in the 'house_type' column
house_sales['house_type'] = house_sales['house_type'].replace({
    'Det.': 'Detached',
    'Semi': 'Semi-detached',
    'Terr.': 'Terraced'
})
house_sales['city'] = house_sales['city'].str.title().str.strip()

# Convert area to numeric after removing 'sq.m.' and trimming
house_sales['area'] = pd.to_numeric(house_sales['area'].str.replace('sq.m.', '').str.strip(), errors='coerce').round(1)

# Final cleaned DataFrame
clean_data = house_sales.copy()

# Display the cleaned data to confirm
clean_data.head(100)

object

    house_id        city  sale_price  ... bedrooms     house_type   area
0    1217792  Silvertown       55943  ...        2  Semi-detached  107.8
1    1900913  Silvertown      384677  ...        5       Detached  498.8
2    1174927   Riverford      281707  ...        6       Detached  542.5
3    1773666  Silvertown      373251  ...        6       Detached  528.4
4    1258487  Silvertown      328885  ...        5       Detached  477.1
..       ...         ...         ...  ...      ...            ...    ...
95   1879053    Teasdale       87891  ...        2  Semi-detached  147.6
96   1079746   Poppleton      162407  ...        3       Detached  293.5
97   1138391   Poppleton      273335  ...        5       Detached  464.4
98   1472754   Riverford      168295  ...        4       Detached  329.0
99   1236600    Teasdale      336904  ...        5       Detached  450.9

[100 rows x 8 columns]

# Task 3 

The team at RealAgents have told you that they have always believed that the number of bedrooms is the biggest driver of house price. 

Producing a table showing the difference in the average sale price by number of bedrooms along with the variance to investigate this question for the team.

 - You should start with the data in the file 'house_sales.csv'.

 - Your output should be a data frame named `price_by_rooms`. 

 - It should include the three columns `bedrooms`, `avg_price`, `var_price`. 

 - Your answers should be rounded to 1 decimal place.

In [38]:

# Calculate average sale price and variance by number of bedrooms

# Group by 'bedrooms' and calculate the mean and variance of 'sale_price'
price_by_rooms = clean_data.groupby('bedrooms')['sale_price'].agg(['mean', 'var']).reset_index()

# Rename the columns to match the required output
price_by_rooms.columns = ['bedrooms', 'avg_price', 'var_price']

# Round the results to 2 decimal places for reporting
price_by_rooms = price_by_rooms.round(1)

# Display the result
price_by_rooms

   bedrooms  avg_price     var_price
0         2    67076.4  5.652896e+08
1         3   154665.1  2.378289e+09
2         4   234704.6  1.725211e+09
3         5   301515.9  2.484328e+09
4         6   375741.3  3.924432e+09

# Task 4

Fit a baseline model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `base_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [39]:

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

# Load the train.csv and validation.csv files
train_data = pd.read_csv('train.csv')
validation_data = pd.read_csv('validation.csv')

# Preprocessing: Replace unconventional missing values in train and validation datasets
train_data.replace(['--', 'missing', 'null'], pd.NA, inplace=True)
validation_data.replace(['---', 'missing', 'null'], pd.NA, inplace=True)

# Define the features and target variable for training
X_train = train_data.drop(columns=['sale_price', 'house_id'])
y_train = train_data['sale_price']

# Define the features for the validation set
X_validation = validation_data.drop(columns=['house_id'])

# Preprocess categorical features using OneHotEncoder and handle missing values
categorical_features = ['city', 'house_type']
numerical_features = ['months_listed', 'bedrooms', 'area']

# Create a preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', SimpleImputer(strategy='mean'), numerical_features),
        ('cat', Pipeline(steps=[
            ('imputer', SimpleImputer(strategy='most_frequent')),
            ('onehot', OneHotEncoder(handle_unknown='ignore'))]), categorical_features)
    ])

# Create a pipeline that first preprocesses the data and then applies linear regression
baseline_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

# Fit the baseline model
baseline_pipeline.fit(X_train, y_train)

# Predict the sale price for the validation data using the baseline model
baseline_predictions = baseline_pipeline.predict(X_validation)

# Create the output dataframe
base_result = pd.DataFrame({
    'house_id': validation_data['house_id'],
    'price': baseline_predictions
})

# Round the predicted prices to 2 decimal places
base_result['price'] = base_result['price'].round(1)

# Display the base_result dataframe
base_result.head()

   house_id     price
0   1331375  121527.8
1   1630115  304386.6
2   1645745  384760.1
3   1336775  123976.3
4   1888274  271186.2

# Task 5

Fit a comparison model to predict the sale price of a house.

 1. Fit your model using the data contained in “train.csv” </br></br>

 2. Use “validation.csv” to predict new values based on your model. You must return a dataframe named `compare_result`, that includes `house_id` and `price`. The price column must be your predicted values.

In [40]:

from sklearn.ensemble import GradientBoostingRegressor

# Fit a comparison model using Gradient Boosting Regressor

# Define the GradientBoostingRegressor model for comparison
comparison_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42)

# Create a pipeline that includes preprocessing and the Gradient Boosting model
comparison_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', comparison_model)
])

# Fit the comparison model
comparison_pipeline.fit(X_train, y_train)

# Predict the sale price for the validation data using the comparison model
comparison_predictions = comparison_pipeline.predict(X_validation)

# Create the output dataframe for comparison model predictions
compare_result = pd.DataFrame({
    'house_id': validation_data['house_id'],
    'price': comparison_predictions
})

# Round the predicted prices to 2 decimal places
compare_result['price'] = compare_result['price'].round(1)

# Display the compare_result dataframe
compare_result.head()

   house_id     price
0   1331375   85087.0
1   1630115  308030.0
2   1645745  394241.0
3   1336775  110838.5
4   1888274  268611.6